import { Experience } from "../types";
import { Icons } from "./icons";

export const Experiences: Experience[] = [
  {
    title: "Founding Engineer",
    type: "self-employed",
    company: "Shiplo",
    startDate: "Jun 2025",
    endDate: "Oct 2025",
    location: "Chicago, IL",
    responsibilities: [
      "Co-built Python server + multi-platform AI-operator platform; shipped v0 in 4 weeks.",
      "Launched GTM from scratch → 304 beta signups in 4 weeks, 100% organic reach.",
      "Owned roadmap, budget, and 3-person eng loop; admitted to Delta Residency & Founder University 11.",
    ],
    icons: [
      Icons.startup,
      Icons.python,
      Icons.fastapi,
      Icons.react,
      Icons.tailwind,
      Icons.electron,
      Icons.reactnative,
      Icons.supabase,
      Icons.docker,
      Icons.growth,
      Icons.ops,
      Icons.sales,
      Icons.gtm,
    ].map(({ name, icon, link }) => ({ name, icon, link })),
    externalLinks: null,
  },
  {
    title: "Full Stack Developer",
    type: "work",
    company: "University of Illinois Chicago",
    startDate: "Sep 2024",
    endDate: "Present Day",
    location: "Chicago, IL",
    responsibilities: [
      "Resolved 14 prod bugs; delivered 8 pages across 2 core modules (React/.NET/SQL Server).",
      "Rewrote and indexed 5 slow SQL/Oracle stored procedures.",
      "Supported CentOS → Red Hat migration, fixing 3 major breaking changes.",
    ],
    icons: [
      Icons.react,
      Icons.node,
      Icons.c_sharp,
      Icons.dot_net,
      Icons.redhat,
      Icons.mssql,
      Icons.oracle,
    ].map(({ name, icon, link }) => ({ name, icon, link })),
    externalLinks: null,
  },
  {
    title: "Founding Engineer",
    type: "self-employed",
    company: "Coffee Logic LLC",
    startDate: "Oct 2024",
    endDate: "May 2025",
    location: "Atlanta, GA",
    responsibilities: [
      "Solo-built cross-platform mobile app with local Python predictive model.",
      "Shipped MVP in 3 weeks; 14 feature releases Q1 via weekly user-feedback sprints.",
      "Implemented 25 customer-requested features in 3 days.",
    ],
    icons: [
      Icons.startup,
      Icons.reactnative,
      Icons.supabase,
      Icons.python,
      Icons.figma,
    ].map(({ name, icon, link }) => ({ name, icon, link })),
    externalLinks: null,
  },
  {
    title: "Software Engineering Intern",
    type: "work",
    company: "Quad City Tennis Club",
    startDate: "May 2023",
    endDate: "Aug 2023",
    location: "Moline, IL",
    responsibilities: [
      "Re-architected website & backend; cut page load 3.2s → 1.1s (≈66% faster).",
      "Ran 6 stakeholder sessions; shipped 5 features on schedule.",
    ],
    icons: [Icons.systems].map(({ name, icon, link }) => ({
      name,
      icon,
      link,
    })),
    externalLinks: null,
  },
  {
    title: "SIG Mobile Development Founder & Lead",
    type: "association",
    company: "Association of Computing Machinery (ACM) @ UIC",
    startDate: "Jun 2024",
    endDate: "Present Day",
    location: "Chicago, IL",
    responsibilities: [
      "Founded and scaled SIG Mobile from 0 → 30+ members.",
      "Ran weekly workshops; led React Native and Flutter dev mentorships.",
      "Guided teams to 1st-place wins at WildHacks, MHacks, and SparkHacks.",
    ],
    icons: [Icons.management, Icons.flutter, Icons.reactnative].map(
      ({ name, icon, link }) => ({ name, icon, link })
    ),
    externalLinks: null,
  },
];
