import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Kuppili</title>
      <meta name="description" content="Generated by create next app" />
      {/* Google tag (gtag.js) */}
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-GW2X2VVGD6"
      />
      <script
        dangerouslySetInnerHTML={{
          __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-GW2X2VVGD6');
            `,
        }}
      />
    </>
  );
}
