import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/montserrat";
import { ThemeWrapper } from "@/themeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeWrapper>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ThemeWrapper>
  );
}
